INSERT INTO Geography (name)
VALUES
    ('Andorra'),
    ('United Arab Emirates'),
    ('Afghanistan'),
    ('Antigua and Barbuda'),
    ('Anguilla'),
    ('Albania'),
    ('Armenia'),
    ('Netherlands Antilles'),
    ('Anla'),
    ('Antarctica'),
    ('Argentina'),
    ('American Samoa'),
    ('Austria'),
    ('Australia'),
    ('Aruba'),
    (N'Åland Islands'),
    ('Azerbaijan'),
    ('Bosnia and Herzegovina'),
    ('Barbados'),
    ('Bangladesh'),
    ('Belgium'),
    ('Burkina Faso'),
    ('Bulgaria'),
    ('Bahrain'),
    ('Burundi'),
    ('Benin'),
    ('Saint Bartholemy'),
    ('Bermuda'),
    ('Brunei'),
    ('Bolivia'),
    ('Bonaire'),
    ('Brazil'),
    ('Bahamas'),
    ('Bhutan'),
    ('Bouvet Island'),
    ('Botswana'),
    ('Belarus'),
    ('Belize'),
    ('Canada'),
    ('Cocos [Keeling] Islands'),
    ('Congo [DRC]'),
    ('Central African Republic'),
    ('Congo [Republic]'),
    ('Switzerland'),
    (N'Côte d''Ivoire'),
    ('Cook Islands'),
    ('Chile'),
    ('Cameroon'),
    ('China'),
    ('Colombia'),
    ('Costa Rica'),
    ('Cuba'),
    ('Cape Verde'),
    (N'Curo'),
    ('Christmas Island'),
    ('Cyprus'),
    ('Czech Republic'),
    ('Germany'),
    ('Djibouti'),
    ('Denmark'),
    ('Dominica'),
    ('Dominican Republic'),
    ('Algeria'),
    ('Ecuador'),
    ('Estonia'),
    ('Egypt'),
    ('Western Sahara'),
    ('Eritrea'),
    ('Spain'),
    ('Ethiopia'),
    ('Finland'),
    ('Fiji'),
    ('Falkland Islands [Islas Malvinas]'),
    ('Micronesia'),
    ('Faroe Islands'),
    ('France'),
    ('Gabon'),
    ('United Kingdom'),
    ('Grenada'),
    ('Georgia'),
    ('French Guiana'),
    ('Guernsey'),
    ('Ghana'),
    ('Gibraltar'),
    ('Greenland'),
    ('Gambia'),
    ('Guinea'),
    ('Guadeloupe'),
    ('Equatorial Guinea'),
    ('Greece'),
    ('South Georgia and the South Sandwich Islands'),
    ('Guatemala'),
    ('Guam'),
    ('Guinea-Bissau'),
    ('Guyana'),
    ('Gaza Strip'),
    ('Hong Kong'),
    ('Heard Island and McDonald Islands'),
    ('Honduras'),
    ('Croatia'),
    ('Haiti'),
    ('Hungary'),
    ('Indonesia'),
    ('Ireland'),
    ('Israel'),
    ('Isle of Man'),
    ('India'),
    ('British Indian Ocean Territory'),
    ('Iraq'),
    ('Iran'),
    ('Iceland'),
    ('Italy'),
    ('Jersey'),
    ('Jamaica'),
    ('Jordan'),
    ('Japan'),
    ('Kenya'),
    ('Kyrgyzstan'),
    ('Cambodia'),
    ('Kiribati'),
    ('Comoros'),
    ('Saint Kitts and Nevis'),
    ('North Korea'),
    ('South Korea'),
    ('Kuwait'),
    ('Cayman Islands'),
    ('Kazakhstan'),
    ('Laos'),
    ('Lebanon'),
    ('Saint Lucia'),
    ('Liechtenstein'),
    ('Sri Lanka'),
    ('Liberia'),
    ('Lesotho'),
    ('Lithuania'),
    ('Luxembourg'),
    ('Latvia'),
    ('Libya'),
    ('Morocco'),
    ('Monaco'),
    ('Moldova'),
    ('Montenegro'),
    ('Saint Martin'),
    ('Madagascar'),
    ('Marshall Islands'),
    ('Macedonia [FYROM]'),
    ('Mali'),
    ('Myanmar [Burma]'),
    ('Mongolia'),
    ('Macau'),
    ('Northern Mariana Islands'),
    ('Martinique'),
    ('Mauritania'),
    ('Montserrat'),
    ('Malta'),
    ('Mauritius'),
    ('Maldives'),
    ('Malawi'),
    ('Mexico'),
    ('Malaysia'),
    ('Mozambique'),
    ('Namibia'),
    ('New Caledonia'),
    ('Niger'),
    ('Norfolk Island'),
    ('Nigeria'),
    ('Nicaragua'),
    ('Netherlands'),
    ('Norway'),
    ('Nepal'),
    ('Nauru'),
    ('Niue'),
    ('New Zealand'),
    ('Oman'),
    ('Panama'),
    ('Peru'),
    ('French Polynesia'),
    ('Papua New Guinea'),
    ('Philippines'),
    ('Pakistan'),
    ('Poland'),
    ('Saint Pierre and Miquelon'),
    ('Pitcairn Islands'),
    ('Puerto Rico'),
    ('Palestinian Territories'),
    ('Portugal'),
    ('Palau'),
    ('Paraguay'),
    ('Qatar'),
    ('Réunion'),
    ('Romania'),
    ('Serbia'),
    ('Russia'),
    ('Rwanda'),
    ('Saudi Arabia'),
    ('Solomon Islands'),
    ('Seychelles'),
    ('Sudan'),
    ('Sweden'),
    ('Singapore'),
    ('Saint Helena'),
    ('Slovenia'),
    ('Svalbard and Jan Mayen'),
    ('Slovakia'),
    ('Sierra Leone'),
    ('San Marino'),
    ('Senegal'),
    ('Somalia'),
    ('Suriname'),
    ('South Sudan'),
    ('São Tomé and Príncipe'),
    ('El Salvador'),
    ('Sint Maarten (Dutch part)'),
    ('Syria'),
    ('Swaziland'),
    ('Turks and Caicos Islands'),
    ('Chad'),
    ('French Southern Territories'),
    ('Togo'),
    ('Thailand'),
    ('Tajikistan'),
    ('Tokelau'),
    ('Timor-Leste'),
    ('Turkmenistan'),
    ('Tunisia'),
    ('Tonga'),
    ('Turkey'),
    ('Trinidad and Tobago'),
    ('Tuvalu'),
    ('Taiwan'),
    ('Tanzania'),
    ('Ukraine'),
    ('Uganda'),
    ('U.S. Minor Outlying Islands'),
    ('United States'),
    ('United States Alaska'),
    ('Uruguay'),
    ('Uzbekistan'),
    ('Vatican City'),
    ('Saint Vincent and the Grenadines'),
    ('Venezuela'),
    ('British Virgin Islands'),
    ('U.S. Virgin Islands'),
    ('Vietnam'),
    ('Vanuatu'),
    ('Wallis and Futuna'),
    ('Samoa'),
    ('Kosovo'),
    ('Yemen'),
    ('Mayotte'),
    ('South Africa'),
    ('Zambia'),
    ('Zimbabwe');

INSERT INTO Geography (name)
VALUES ('Africa'), -- 254
       ('Northern Africa'), -- 255
       ('Western Africa'), -- 256
       ('Middle Africa'), -- 257
       ('Eastern Africa'), -- 258
       ('Southern Africa'), -- 259
       ('Americas'), -- 260
       ('Americas including Greenland'), -- 261
       ('Northern America'), -- 262
       ('Caribbean'), -- 263
       ('Central America'), -- 264
       ('South America'), -- 265
       ('APAC'), -- 266, Asia Pacific
       ('Asia'), -- 267
       ('Central Asia'), -- 268
       ('Eastern Asia'), -- 269
       ('Southern Asia'), -- 270
       ('Southeastern Asia'), -- 271
       ('Western Asia'), -- 272
       ('APJC'), -- 273, Asia Pacific, Japan and China
       ('ANZ'), -- 274, Australia and New Zealand only
       ('Benelux'), -- 275
       ('BRICS'), -- 276, Brazil, Russia, India, China, and South Africa
       ('DACH'), -- 277, Germany (Deutschland), Austria, and Switzerland
       ('EMEA'), -- 278, Europe, the Middle East, and Africa
       ('European Union'), -- 279
       ('Europe'), -- 280
       ('Northern Europe'), -- 281
       ('Western Europe'), -- 282
       ('Eastern Europe'), -- 283
       ('Southern Europe'), -- 284
       ('Oceania'), -- 285
       ('Australia and New Zealand'), -- 286 Same as ANZ but with Norfolk Island as well
       ('Melanesia'), -- 287
       ('Micronesia'), -- 288
       ('Polynesia'), -- 289
       ('NORAM'); -- 290 North America; US, Canada, and sometimes Mexico