INSERT INTO dbo.project (project_id,
                         project_name,
                         project_sales_number,
                         project_description,
                         project_day_rate,
                         project_gross_margin,
                         project_price,
                         project_start_date,
                         project_end_date,
                         project_total_days,
                         project_location)
VALUES ('769f922a-6e19-40d5-b46d-8ebd43960736',
        'Cheap Project',
        '123456',
        'Some poor people wanted help',
        228.8,
        30,
        2974.4,
        '2024-12-02',
        '2024-12-13',
        10,
        60
       );