
name: Run tests

on:
  pull_request:
    branches: [ "master", "Deployment" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up JDK 21 for Backend
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    # Setup application.properties
    - name: Create application.properties from Template
      run: |
        cp src/main/resources/application.example.properties src/main/resources/application.properties
        sed -i "s|spring.datasource.url=|spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }}|g" src/main/resources/application.properties
        sed -i "s|spring.datasource.username=|spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }}|g" src/main/resources/application.properties
        sed -i "s|spring.datasource.password=|spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}|g" src/main/resources/application.properties
        sed -i "s|jwt.secret=|jwt.secret=${{ secrets.JWT_SECRET }}|g" src/main/resources/application.properties
        
    # Build Backend with Maven
    #- name: Build Backend
    #  run: mvn -B package --file pom.xml

    # Set up Node.js for Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/FE/package-lock.json

    # Install and Build Frontend
    - name: Install Frontend Dependencies
      working-directory: src/FE
      run: npm ci

    - name: Build Frontend
      working-directory: src/FE
      run: npm run build --prod

    # Install TestCafe
    - name: Install TestCafe
      run: npm install -g testcafe

    # Start Backend Server
    - name: Start Backend
      run: |
        nohup mvn spring-boot:run -Dspring-boot.run.profiles=test > backend.log 2>&1 &
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Wait for Backend to Start
      run: |
        timeout 70 bash -c 'until echo > /dev/tcp/localhost/8080; do sleep 1; done' || false

    # Serve Frontend Locally
    - name: Install and Configure Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo rm /etc/nginx/sites-enabled/default
        echo "
        server {
            listen 4200;
            server_name localhost;
        
            root $GITHUB_WORKSPACE/src/FE/dist/fe/browser;
            index index.html;
        
            location / {
                try_files \$uri \$uri/ /index.html;
            }
        }
        " | sudo tee /etc/nginx/sites-available/frontend
        sudo ln -s /etc/nginx/sites-available/frontend /etc/nginx/sites-enabled/frontend
        sudo nginx -t
        sudo systemctl restart nginx

    - name: Wait for Frontend
      run: |
        timeout 30 bash -c 'until echo > /dev/tcp/localhost/4200; do sleep 1; done' || false

    # Run TestCafe E2E Tests
    - name: Run E2E Tests with TestCafe
      run: |
        testcafe chrome:headless src/test/*.js --reporter spec


    # Clean Up
    - name: Stop Backend and Frontend
      run: |
        pkill -f 'java -jar'
        pkill -f 'http-server'
